


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_cron" WITH SCHEMA "pg_catalog";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."apply_inactivity_penalties"() RETURNS "void"
    LANGUAGE "plpgsql"
    AS $$
DECLARE
  player_record RECORD;
  latest_match_date TIMESTAMPTZ;
  days_inactive INTEGER;
BEGIN
  -- Cicliamo su tutti i giocatori
  FOR player_record IN SELECT * FROM players LOOP
    
    -- Troviamo l'ultima partita completata a cui ha partecipato il giocatore
    SELECT MAX(created_at) INTO latest_match_date
    FROM matches
    WHERE status = 'completed' 
      AND (team_a_left_id = player_record.id 
           OR team_a_right_id = player_record.id 
           OR team_b_left_id = player_record.id 
           OR team_b_right_id = player_record.id);

    -- Se non ha mai giocato una partita completata, usiamo la data in cui è stato creato il suo profilo
    IF latest_match_date IS NULL THEN
      latest_match_date := player_record.created_at;
    END IF;

    -- Calcoliamo i giorni di inattività rispetto ad oggi
    days_inactive := CURRENT_DATE - latest_match_date::date;

    -- Se sono passati 60 giorni (2 mesi) o più, decurtiamo 0.10 dal ranking
    IF days_inactive >= 60 THEN
      UPDATE players 
      SET ranking = ranking - 0.10 
      WHERE id = player_record.id;
    END IF;

  END LOOP;
END;
$$;


ALTER FUNCTION "public"."apply_inactivity_penalties"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."audit_logs" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "admin_id" "uuid",
    "admin_name" character varying(255),
    "action_type" character varying(50),
    "target_player_id" bigint,
    "details" "text",
    "entity_id" "text",
    "metadata" "jsonb" DEFAULT '{}'::"jsonb"
);


ALTER TABLE "public"."audit_logs" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."audit_logs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."audit_logs_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."audit_logs_id_seq" OWNED BY "public"."audit_logs"."id";



CREATE TABLE IF NOT EXISTS "public"."clubs" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "address" "text",
    "maps_url" "text",
    "city" "text"
);


ALTER TABLE "public"."clubs" OWNER TO "postgres";


ALTER TABLE "public"."clubs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."clubs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."matches" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "match_date" timestamp with time zone,
    "team_a_left_id" bigint,
    "team_a_right_id" bigint,
    "team_b_left_id" bigint,
    "team_b_right_id" bigint,
    "status" "text" DEFAULT 'pending'::"text",
    "winning_team" "text",
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "score" "jsonb" DEFAULT '[]'::"jsonb",
    "match_type" character varying(15) DEFAULT 'male'::character varying,
    "club_id" bigint,
    CONSTRAINT "matches_match_type_check" CHECK ((("match_type")::"text" = ANY ((ARRAY['male'::character varying, 'female'::character varying, 'mixed'::character varying])::"text"[]))),
    CONSTRAINT "matches_status_check" CHECK (("status" = ANY (ARRAY['pending'::"text", 'completed'::"text", 'canceled'::"text"]))),
    CONSTRAINT "matches_winning_team_check" CHECK (("winning_team" = ANY (ARRAY['A'::"text", 'B'::"text"])))
);


ALTER TABLE "public"."matches" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."players" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "first_name" "text",
    "last_name" "text",
    "preferred_side" "text" NOT NULL,
    "ranking" double precision DEFAULT '4.5'::double precision NOT NULL,
    "absence_days" integer,
    "role" "text" DEFAULT 'user'::"text",
    "user_id" "uuid",
    "dominant_hand" character varying(10) DEFAULT 'Destro'::character varying,
    "phone" character varying(20),
    "gender" character varying(1) DEFAULT 'M'::character varying,
    "avatar_url" "text",
    CONSTRAINT "players_gender_check" CHECK ((("gender")::"text" = ANY ((ARRAY['M'::character varying, 'F'::character varying])::"text"[]))),
    CONSTRAINT "players_preferred_side_check" CHECK (("preferred_side" = ANY (ARRAY['Left'::"text", 'Right'::"text", 'Both'::"text"]))),
    CONSTRAINT "players_role_check" CHECK (("role" = ANY (ARRAY['user'::"text", 'admin'::"text"])))
);


ALTER TABLE "public"."players" OWNER TO "postgres";


ALTER TABLE "public"."players" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."players_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE OR REPLACE VIEW "public"."view_player_stats" AS
 WITH "player_match_aggregates" AS (
         SELECT "p"."id",
            "p"."first_name",
            "p"."last_name",
            "p"."ranking",
            "p"."preferred_side",
            "p"."gender",
            "p"."avatar_url",
            COALESCE(( SELECT "count"(*) AS "count"
                   FROM "public"."matches" "m"
                  WHERE (("m"."status" = 'completed'::"text") AND (((("p"."id" = "m"."team_a_left_id") OR ("p"."id" = "m"."team_a_right_id")) OR ("p"."id" = "m"."team_b_left_id")) OR ("p"."id" = "m"."team_b_right_id")))), (0)::bigint) AS "total_played",
            COALESCE(( SELECT "count"(*) AS "count"
                   FROM "public"."matches" "m"
                  WHERE (("m"."status" = 'completed'::"text") AND (((("p"."id" = "m"."team_a_left_id") OR ("p"."id" = "m"."team_a_right_id")) AND ("m"."winning_team" = 'A'::"text")) OR ((("p"."id" = "m"."team_b_left_id") OR ("p"."id" = "m"."team_b_right_id")) AND ("m"."winning_team" = 'B'::"text"))))), (0)::bigint) AS "matches_won"
           FROM "public"."players" "p"
        )
 SELECT "id",
    "first_name",
    "last_name",
    "ranking",
    "preferred_side",
    "gender",
    "avatar_url",
    "total_played",
        CASE
            WHEN ("total_played" = 0) THEN 0.0
            ELSE "round"(((("matches_won")::numeric / ("total_played")::numeric) * (100)::numeric), 1)
        END AS "win_rate"
   FROM "player_match_aggregates";


ALTER VIEW "public"."view_player_stats" OWNER TO "postgres";


ALTER TABLE ONLY "public"."audit_logs" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."audit_logs_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."audit_logs"
    ADD CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."clubs"
    ADD CONSTRAINT "clubs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."matches"
    ADD CONSTRAINT "matches_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."players"
    ADD CONSTRAINT "players_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."players"
    ADD CONSTRAINT "unique_user_id" UNIQUE ("user_id");



CREATE INDEX "idx_audit_logs_entity_id" ON "public"."audit_logs" USING "btree" ("entity_id");



CREATE INDEX "idx_audit_logs_metadata" ON "public"."audit_logs" USING "gin" ("metadata");



ALTER TABLE ONLY "public"."audit_logs"
    ADD CONSTRAINT "audit_logs_admin_id_fkey" FOREIGN KEY ("admin_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."matches"
    ADD CONSTRAINT "matches_club_id_fkey" FOREIGN KEY ("club_id") REFERENCES "public"."clubs"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."matches"
    ADD CONSTRAINT "matches_team_a_left_id_fkey" FOREIGN KEY ("team_a_left_id") REFERENCES "public"."players"("id");



ALTER TABLE ONLY "public"."matches"
    ADD CONSTRAINT "matches_team_a_right_id_fkey" FOREIGN KEY ("team_a_right_id") REFERENCES "public"."players"("id");



ALTER TABLE ONLY "public"."matches"
    ADD CONSTRAINT "matches_team_b_left_id_fkey" FOREIGN KEY ("team_b_left_id") REFERENCES "public"."players"("id");



ALTER TABLE ONLY "public"."matches"
    ADD CONSTRAINT "matches_team_b_right_id_fkey" FOREIGN KEY ("team_b_right_id") REFERENCES "public"."players"("id");



ALTER TABLE ONLY "public"."players"
    ADD CONSTRAINT "players_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



CREATE POLICY "Allow public insert on matches" ON "public"."matches" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow public read access" ON "public"."players" FOR SELECT USING (true);



CREATE POLICY "Allow public read access on matches" ON "public"."matches" FOR SELECT USING (true);



CREATE POLICY "Allow public update on matches" ON "public"."matches" FOR UPDATE USING (true);



CREATE POLICY "Allow public update on players" ON "public"."players" FOR UPDATE USING (true);



CREATE POLICY "Consentiti inserimenti agli utenti autenticati" ON "public"."players" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Consentito eliminare i propri match in programma" ON "public"."matches" FOR DELETE TO "authenticated" USING ((("status" = 'pending'::"text") AND (EXISTS ( SELECT 1
   FROM "public"."players"
  WHERE (("players"."user_id" = "auth"."uid"()) AND (("players"."id" = "matches"."team_a_left_id") OR ("players"."id" = "matches"."team_a_right_id") OR ("players"."id" = "matches"."team_b_left_id") OR ("players"."id" = "matches"."team_b_right_id") OR ("players"."role" = 'admin'::"text")))))));



CREATE POLICY "Enable delete for authenticated users only" ON "public"."clubs" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."clubs" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable read access for all users" ON "public"."clubs" FOR SELECT USING (true);



CREATE POLICY "Enable update for authenticated users only" ON "public"."clubs" FOR UPDATE TO "authenticated" USING (true);



CREATE POLICY "Log inseribili da utenti autenticati" ON "public"."audit_logs" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Log visibili agli utenti autenticati" ON "public"."audit_logs" FOR SELECT TO "authenticated" USING (true);



ALTER TABLE "public"."audit_logs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."clubs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."matches" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."players" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."players";






GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";











































































































































































GRANT ALL ON FUNCTION "public"."apply_inactivity_penalties"() TO "anon";
GRANT ALL ON FUNCTION "public"."apply_inactivity_penalties"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."apply_inactivity_penalties"() TO "service_role";
























GRANT ALL ON TABLE "public"."audit_logs" TO "anon";
GRANT ALL ON TABLE "public"."audit_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."audit_logs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."audit_logs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."audit_logs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."audit_logs_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."clubs" TO "anon";
GRANT ALL ON TABLE "public"."clubs" TO "authenticated";
GRANT ALL ON TABLE "public"."clubs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."clubs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."clubs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."clubs_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."matches" TO "anon";
GRANT ALL ON TABLE "public"."matches" TO "authenticated";
GRANT ALL ON TABLE "public"."matches" TO "service_role";



GRANT ALL ON TABLE "public"."players" TO "anon";
GRANT ALL ON TABLE "public"."players" TO "authenticated";
GRANT ALL ON TABLE "public"."players" TO "service_role";



GRANT ALL ON SEQUENCE "public"."players_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."players_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."players_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."view_player_stats" TO "anon";
GRANT ALL ON TABLE "public"."view_player_stats" TO "authenticated";
GRANT ALL ON TABLE "public"."view_player_stats" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";

alter table "public"."matches" drop constraint "matches_match_type_check";

alter table "public"."players" drop constraint "players_gender_check";

alter table "public"."matches" add constraint "matches_match_type_check" CHECK (((match_type)::text = ANY ((ARRAY['male'::character varying, 'female'::character varying, 'mixed'::character varying])::text[]))) not valid;

alter table "public"."matches" validate constraint "matches_match_type_check";

alter table "public"."players" add constraint "players_gender_check" CHECK (((gender)::text = ANY ((ARRAY['M'::character varying, 'F'::character varying])::text[]))) not valid;

alter table "public"."players" validate constraint "players_gender_check";

create or replace view "public"."view_player_stats" as  WITH player_match_aggregates AS (
         SELECT p.id,
            p.first_name,
            p.last_name,
            p.ranking,
            p.preferred_side,
            p.gender,
            p.avatar_url,
            COALESCE(( SELECT count(*) AS count
                   FROM public.matches m
                  WHERE ((m.status = 'completed'::text) AND ((((p.id = m.team_a_left_id) OR (p.id = m.team_a_right_id)) OR (p.id = m.team_b_left_id)) OR (p.id = m.team_b_right_id)))), (0)::bigint) AS total_played,
            COALESCE(( SELECT count(*) AS count
                   FROM public.matches m
                  WHERE ((m.status = 'completed'::text) AND ((((p.id = m.team_a_left_id) OR (p.id = m.team_a_right_id)) AND (m.winning_team = 'A'::text)) OR (((p.id = m.team_b_left_id) OR (p.id = m.team_b_right_id)) AND (m.winning_team = 'B'::text))))), (0)::bigint) AS matches_won
           FROM public.players p
        )
 SELECT id,
    first_name,
    last_name,
    ranking,
    preferred_side,
    gender,
    avatar_url,
    total_played,
        CASE
            WHEN (total_played = 0) THEN 0.0
            ELSE round((((matches_won)::numeric / (total_played)::numeric) * (100)::numeric), 1)
        END AS win_rate
   FROM player_match_aggregates;



  create policy "Aggiornamento pubblico avatars"
  on "storage"."objects"
  as permissive
  for update
  to anon, authenticated
using ((bucket_id = 'avatars'::text));



  create policy "Eliminazione avatars utenti registrati"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using ((bucket_id = 'avatars'::text));



  create policy "Inserimento pubblico avatars"
  on "storage"."objects"
  as permissive
  for insert
  to anon, authenticated
with check ((bucket_id = 'avatars'::text));



  create policy "Lettura pubblica avatars"
  on "storage"."objects"
  as permissive
  for select
  to anon, authenticated
using ((bucket_id = 'avatars'::text));



